In [1]:
#python es un lenguaje interpretado, a diferencia de lenguajes complilados programas en python se ejecutan al
#momento de correr el codigo, no tiene que complilarse.

#Jupyter notebook nos permite realizar codigo de una manera mas interactiva y podemos correr partes de codigo celda
#por celda, presiona el boton de run que se encuentra arriba o SHIFT+RETURN para ejecutar la celda seleccionada

#Para poner comentarios se pone gato seguido por el comentario

## Variables de entrada



a= 1.03 #en anaconda no es necesario declarar el tipo de dato, se obtiene por contexto
b=503
c= 2** 2  #elevar a la n se escribe con '**' 
print("a= "+str(a)+" b= "+str(b)+" c= "+str(c)) #str convierte un dato en un string y asi se puede concatenar e
#imprimir junto con texto

a= 1.03 b= 503 c= 4


In [2]:
## Suma 
d= a+b
e= a+c
f= d+e-b
print("d= "+str(d)+" e= "+str(e)+" f= "+str(f))

d= 504.03 e= 5.03 f= 6.059999999999945


In [3]:
## Multiplicación 
ab= a*b
bc= b*c
g= f*(-a)
h= f/a
print("ab= "+str(ab)+" bc= "+str(bc)+" g= "+str(g)+" h= "+str(h))

ab= 518.09 bc= 2012 g= -6.241799999999944 h= 5.883495145631015


In [4]:
import numpy as np #por si solo python no tiene arreglos como en c++ pero con la libreria numpy se puede obtener
#esta funcionalidad con el comando 'import' declaramos que queremos importar una libreria y con 'as' le asignamos
#el alias de 'np', numpy es una libreria muy extensa y muy versatil para operaciones numericas solo veremos algunos
#de los mas comunes


A= [0,1,2,3,4,5]
B= np.zeros(6)
C= np.ones(6)
D= np.matrix([[0,1,2,3,4,5],[6,7,8,9,10,11]])
E= [[1,0],[0,1]]

In [6]:
# Suma
F= np.sum([0.5, 1.5])#con np.sum se suman todos los terminos del vector o matriz
G= np.sum([D,D])
print("A= "+str(A)+" B= "+str(B)+" C= "+str(C)+" D= "+str(D))
print("E= "+str(E)+" F= "+str(F)+" G= "+str(G))

A= [0, 1, 2, 3, 4, 5] B= [0. 0. 0. 0. 0. 0.] C= [1. 1. 1. 1. 1. 1.] D= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
E= [[1, 0], [0, 1]] F= 2.0 G= 132


In [7]:
# Multiplicación
x1 = np.arange(9.0).reshape((3, 3))#np.arrange crea un vector empezando desde 0 hasta n np.reshape te permite 
#cambiar las dimensiones del arreglo
print(x1)
x2 = np.arange(3.0)
print(x2)
np.multiply(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [9]:
# Producto punto
H = np.eye(2)#p.eye crea una matriz identidad de NxN
I = np.ones((2, 2)) * 2
J= H.dot(I)
print(J)

[[2. 2.]
 [2. 2.]]
